/*-
 * SPDX-License-Identifier: BSD 3-Clause License
 *
 * Copyright (c) 2026 deadcafe.beef@gmail.com
 * All rights reserved.
 *
 * ft_table_generate.h - GENERATE macro for per-variant table implementations.
 *
 * Usage in .c files:
 *
 *   #include "flow4_table.h"
 *   // define layout hooks, hash_fn, cmp ...
 *   #include "ft_table_generate.h"
 *
 *   FT_TABLE_GENERATE(flow4, ft_flow4_hash_fn, ft_flow4_cmp)
 */

#ifndef _FT_TABLE_GENERATE_H_
#define _FT_TABLE_GENERATE_H_

#include <string.h>
#include <rix/rix_hash_slot.h>

/*===========================================================================
 * Token-paste helpers
 *===========================================================================*/
#define _FTG_CAT2(a, b)  a##b
#define _FTG_CAT(a, b)   _FTG_CAT2(a, b)

#define _FTG_HT(p, name)   _FTG_CAT(ft_, _FTG_CAT(p, _ht_##name))
#define _FTG_INT(p, name)   _FTG_CAT(ft_, _FTG_CAT(p, _##name))

#ifdef FT_ARCH_SUFFIX
#define _FTG_API(p, name)  _FTG_CAT(_FTG_CAT(ft_, _FTG_CAT(p, _table_##name)), FT_ARCH_SUFFIX)
#else
#define _FTG_API(p, name)  _FTG_CAT(ft_, _FTG_CAT(p, _table_##name))
#endif

#define _FTG_KEY_T(p)       struct _FTG_CAT(p, _key)
#define _FTG_RESULT_T(p)    struct ft_table_result
#ifndef FTG_ENTRY_TYPE
#define FTG_ENTRY_TYPE(p)   struct _FTG_CAT(ft_, _FTG_CAT(p, _entry))
#endif
#define _FTG_ENTRY_T(p)     FTG_ENTRY_TYPE(p)
#define _FTG_TABLE_T(p)     struct _FTG_CAT(ft_, _FTG_CAT(p, _table))
#define _FTG_CONFIG_T(p)    struct ft_table_config
#define _FTG_STATS_T(p)     struct ft_table_stats
#define _FTG_HT_T(p)        struct _FTG_CAT(ft_, _FTG_CAT(p, _ht))

/*===========================================================================
 * FCORE function name helper
 *===========================================================================*/
#define _FTG_FCORE(p, name) _FCORE_CAT(_fcore_, _FCORE_CAT(p, _##name))

/*===========================================================================
 * Entry validity / metadata hooks (overridable per-variant)
 *
 * cur_hash != 0 means "linked in a bucket".
 *===========================================================================*/
#ifndef FTG_ENTRY_IS_ACTIVE
#define FTG_ENTRY_IS_ACTIVE(entry, flag_active)                               \
    ((entry)->meta.cur_hash != 0u)
#endif

#ifndef FTG_ON_INSERT_SUCCESS
#define FTG_ON_INSERT_SUCCESS(entry, flag_active) (void)0
#endif

#ifndef FTG_ENTRY_META_CLEAR_TAIL
#define FTG_ENTRY_META_CLEAR_TAIL(entry)                                      \
    memset((entry)->reserved0, 0, sizeof((entry)->reserved0))
#endif

/*===========================================================================
 * Layout hooks (overridable per-variant before #include)
 *===========================================================================*/
#ifndef FTG_LAYOUT_INIT_STORAGE
#define FTG_LAYOUT_INIT_STORAGE(ft, array, stride, entry_offset)              \
    do {                                                                      \
        (void)(stride);                                                       \
        (void)(entry_offset);                                                 \
        (ft)->pool = (array);                                                 \
    } while (0)
#endif

#ifndef FTG_LAYOUT_HASH_BASE
#define FTG_LAYOUT_HASH_BASE(ft) ((ft)->pool)
#endif

#ifndef FTG_LAYOUT_ENTRY_PTR
#define FTG_LAYOUT_ENTRY_PTR(ft, idx)                                         \
    (((unsigned)(idx) != RIX_NIL) ? &((ft)->pool[(unsigned)(idx) - 1u]) : NULL)
#endif

#ifndef FTG_LAYOUT_ENTRY_INDEX
#define FTG_LAYOUT_ENTRY_INDEX(ft, entry) RIX_IDX_FROM_PTR((ft)->pool, (entry))
#endif

#ifndef FTG_LAYOUT_ENTRY_AT
#define FTG_LAYOUT_ENTRY_AT(ft, off0) (&((ft)->pool[(off0)]))
#endif

/*===========================================================================
 * Pipeline geometry
 *===========================================================================*/
#ifndef FT_TABLE_BULK_STEP_KEYS
#define FT_TABLE_BULK_STEP_KEYS 8u
#endif

#ifndef FT_TABLE_BULK_AHEAD_STEPS
#define FT_TABLE_BULK_AHEAD_STEPS 4u
#endif

#define FT_TABLE_BULK_AHEAD_KEYS                                              \
    (FT_TABLE_BULK_STEP_KEYS * FT_TABLE_BULK_AHEAD_STEPS)

#ifndef FT_TABLE_BULK_CTX_RING
#define FT_TABLE_BULK_CTX_RING 128u
#endif

#ifndef FT_TABLE_GROW_OLD_BK_AHEAD
#define FT_TABLE_GROW_OLD_BK_AHEAD 2u
#endif

#ifndef FT_TABLE_GROW_REINSERT_AHEAD
#define FT_TABLE_GROW_REINSERT_AHEAD 8u
#endif

#ifndef FT_TABLE_GROW_CTX_RING
#define FT_TABLE_GROW_CTX_RING 64u
#endif

/*===========================================================================
 * Bulk-op body macros
 *
 * These are called from inside FT_TABLE_GENERATE via _FTG_*_BODY macros.
 * They delegate to _fcore_<p>_*_ functions generated by FCORE_GENERATE.
 *===========================================================================*/

/* sizeof(ft_table_result) == sizeof(u32): safe to pass &results[0].entry_idx */
#define _FTG_FIND_BULK_BODY(p, ft, keys, nb_keys, now, results, hash_fn, cmp_fn) \
    _FTG_FCORE(p, find_key_bulk_)((ft), (keys), (nb_keys), (now),             \
                              &(results)[0].entry_idx)

#define _FTG_ADD_ENTRY_BULK_BODY(p, ft, entry_idxv, nb_keys, results,         \
                                 hash_fn, cmp_fn)                             \
    _FTG_FCORE(p, add_idx_bulk_)((ft), (entry_idxv), (nb_keys), 0u,           \
                                 &(results)[0].entry_idx)

#define _FTG_ADD_ENTRY_BULK2_BODY(p, ft, entry_idxv, nb_keys, policy,        \
                                  now, unused_idxv, hash_fn, cmp_fn)         \
    return _FTG_FCORE(p, add_idx_bulk_)((ft), (entry_idxv), (nb_keys),       \
                                         (policy), (now), (unused_idxv))

#define _FTG_WALK_BODY(p, ft, cb, arg)                                        \
    return _FTG_FCORE(p, walk_)((ft), (cb), (arg))

#define _FTG_FLUSH_BODY(p, ft)                                                \
    _FTG_FCORE(p, flush_)(ft)

#define _FTG_DEL_KEY_BULK_BODY(p, ft, keys, nb_keys, unused_idxv,             \
                               hash_fn, cmp_fn)                              \
    return _FTG_FCORE(p, del_key_bulk_)((ft), (keys), (nb_keys),             \
                                         (unused_idxv))

#define _FTG_DEL_ENTRY_IDX_BULK_BODY(p, ft, entry_idxv, nb_keys)              \
    _FTG_FCORE(p, del_idx_bulk_)((ft), (entry_idxv), (nb_keys))

/*===========================================================================
 * FT_TABLE_GENERATE(prefix, default_min_nb_bk, default_max_nb_bk,
 *                   default_grow_fill_pct, flag_active, hash_fn, cmp_fn)
 *
 * flag_active is unused (kept for signature compatibility).
 * Bulk operations delegate to the FCORE_GENERATE functions (_fcore_<p>_*).
 * Entry validity is determined by cur_hash != 0 (bucket linkage).
 *===========================================================================*/
#define FT_TABLE_GENERATE(p, default_min_nb_bk, default_max_nb_bk,            \
                          default_grow_fill_pct, flag_active, hash_fn, cmp_fn) \
                                                                               \
/* --- Internal helpers -------------------------------------------------- */ \
                                                                               \
static inline _FTG_ENTRY_T(p) *                                               \
_FTG_INT(p, hash_base_)(_FTG_TABLE_T(p) *ft)                                  \
{                                                                             \
    return (_FTG_ENTRY_T(p) *)(void *)ft;                                     \
}                                                                             \
                                                                               \
static inline int                                                             \
_FTG_INT(p, entry_is_active_)(const _FTG_ENTRY_T(p) *entry)                   \
{                                                                             \
    return FTG_ENTRY_IS_ACTIVE(entry, flag_active);                           \
}                                                                             \
                                                                               \
static inline void                                                            \
_FTG_INT(p, entry_meta_clear_)(_FTG_ENTRY_T(p) *entry)                        \
{                                                                             \
    entry->meta.cur_hash = 0u;                                                \
    entry->meta.slot = 0u;                                                    \
    flow_timestamp_clear(&entry->meta);                                       \
    FTG_ENTRY_META_CLEAR_TAIL(entry);                                         \
}                                                                             \
                                                                               \
static inline unsigned                                                        \
_FTG_INT(p, default_start_nb_bk_)(unsigned max_entries)                       \
{                                                                             \
    unsigned hinted;                                                          \
    hinted = (max_entries + (RIX_HASH_BUCKET_ENTRY_SZ - 1u))                  \
           / RIX_HASH_BUCKET_ENTRY_SZ;                                        \
    if (hinted < (default_min_nb_bk))                                         \
        hinted = (default_min_nb_bk);                                         \
    return ft_roundup_pow2_u32(hinted);                                       \
}                                                                             \
                                                                               \
static inline unsigned                                                        \
_FTG_INT(p, required_nb_bk_)(unsigned entries, unsigned fill_pct)             \
{                                                                             \
    u64 need_slots;                                                      \
    unsigned need_bk;                                                         \
    if (entries == 0u)                                                        \
        return (default_min_nb_bk);                                           \
    need_slots = ((u64)entries * 100u + (u64)fill_pct - 1u)         \
               / (u64)fill_pct;                                          \
    need_bk = (unsigned)((need_slots                                          \
               + (u64)RIX_HASH_BUCKET_ENTRY_SZ - 1u)                     \
               / (u64)RIX_HASH_BUCKET_ENTRY_SZ);                         \
    if (need_bk < (default_min_nb_bk))                                        \
        need_bk = (default_min_nb_bk);                                        \
    return ft_roundup_pow2_u32(need_bk);                                      \
}                                                                             \
                                                                               \
static inline size_t                                                          \
_FTG_INT(p, bucket_bytes_)(unsigned nb_bk)                                    \
{                                                                             \
    return (size_t)nb_bk * sizeof(struct rix_hash_bucket_s);                  \
}                                                                             \
                                                                               \
static int                                                                    \
_FTG_INT(p, alloc_buckets_)(_FTG_TABLE_T(p) *ft,                              \
                            unsigned nb_bk,                                   \
                            struct rix_hash_bucket_s **out)                   \
{                                                                             \
    size_t bytes = _FTG_INT(p, bucket_bytes_)(nb_bk);                         \
    void *ptr;                                                                \
    ptr = ft->bucket_alloc.alloc(bytes,                                       \
                                 _Alignof(struct rix_hash_bucket_s),          \
                                 ft->bucket_alloc.arg);                       \
    if (ptr == NULL)                                                          \
        return -1;                                                            \
    memset(ptr, 0, bytes);                                                    \
    *out = (struct rix_hash_bucket_s *)ptr;                                   \
    return 0;                                                                 \
}                                                                             \
                                                                               \
static inline void                                                            \
_FTG_INT(p, init_storage_)(_FTG_TABLE_T(p) *ft, void *array,                  \
                           size_t stride, size_t entry_offset)                \
{                                                                             \
    FTG_LAYOUT_INIT_STORAGE(ft, array, stride, entry_offset);                 \
}                                                                             \
                                                                               \
/* find_hashed_: single-key lookup using precomputed hash */                  \
static inline _FTG_ENTRY_T(p) *                                               \
_FTG_INT(p, find_hashed_)(_FTG_TABLE_T(p) *ft,                                \
                          const _FTG_KEY_T(p) *key,                           \
                          union rix_hash_hash_u h)                            \
{                                                                             \
    unsigned bk0, bk1;                                                        \
    u32 fp;                                                                   \
    u32 hits;                                                                 \
                                                                               \
    fp = rix_hash_fp(h, ft->ht_head.rhh_mask, &bk0, &bk1);              \
    hits = RIX_HASH_FIND_U32X16(ft->buckets[bk0].hash, fp);                  \
    while (hits != 0u) {                                                      \
        unsigned bit = (unsigned)__builtin_ctz(hits);                         \
        unsigned idx = ft->buckets[bk0].idx[bit];                             \
        _FTG_ENTRY_T(p) *entry;                                               \
        hits &= hits - 1u;                                                    \
        if (idx == (unsigned)RIX_NIL)                                         \
            continue;                                                         \
        entry = FTG_LAYOUT_ENTRY_PTR(ft, idx);                                \
        RIX_ASSUME_NONNULL(entry);                                            \
        if (cmp_fn(&entry->key, key) == 0)                                    \
            return entry;                                                     \
    }                                                                         \
    if (bk1 == bk0)                                                           \
        return NULL;                                                          \
    hits = RIX_HASH_FIND_U32X16(ft->buckets[bk1].hash, fp);                  \
    while (hits != 0u) {                                                      \
        unsigned bit = (unsigned)__builtin_ctz(hits);                         \
        unsigned idx = ft->buckets[bk1].idx[bit];                             \
        _FTG_ENTRY_T(p) *entry;                                               \
        hits &= hits - 1u;                                                    \
        if (idx == (unsigned)RIX_NIL)                                         \
            continue;                                                         \
        entry = FTG_LAYOUT_ENTRY_PTR(ft, idx);                                \
        RIX_ASSUME_NONNULL(entry);                                            \
        if (cmp_fn(&entry->key, key) == 0)                                    \
            return entry;                                                     \
    }                                                                         \
    return NULL;                                                              \
}                                                                             \
                                                                               \
/* insert_hashed_: insert pre-hashed entry into hash table */                 \
static inline int                                                             \
_FTG_INT(p, insert_hashed_)(_FTG_TABLE_T(p) *ft,                              \
                            _FTG_ENTRY_T(p) *entry,                           \
                            const union rix_hash_hash_u h,                    \
                            u32 *entry_idx_out)                          \
{                                                                             \
    _FTG_ENTRY_T(p) *ret;                                                     \
    ret = _FTG_HT(p, insert_hashed)(&ft->ht_head, ft->buckets,                \
                                     _FTG_INT(p, hash_base_)(ft),             \
                                     entry, h);                               \
    if (ret == NULL) {                                                        \
        FTG_ON_INSERT_SUCCESS(entry, flag_active);                            \
        *entry_idx_out = FTG_LAYOUT_ENTRY_INDEX(ft, entry);                   \
        return 0;                                                             \
    }                                                                         \
    if (ret != entry) {                                                       \
        *entry_idx_out = FTG_LAYOUT_ENTRY_INDEX(ft, ret);                     \
        return 1; /* duplicate found */                                       \
    }                                                                         \
    *entry_idx_out = 0u;                                                      \
    return -1; /* table full */                                               \
}                                                                             \
                                                                               \
/* rehash_insert_hashed_: for grow_2x, insert into new bucket array */        \
static inline int                                                             \
_FTG_INT(p, rehash_insert_hashed_)(_FTG_HT_T(p) *head,                        \
                                   struct rix_hash_bucket_s *buckets,         \
                                   _FTG_TABLE_T(p) *ft,                       \
                                   _FTG_ENTRY_T(p) *entry,                    \
                                   union rix_hash_hash_u h)                   \
{                                                                             \
    unsigned mask = head->rhh_mask;                                           \
    unsigned bk0, bk1;                                                        \
    u32 fp;                                                                   \
    fp = rix_hash_fp(h, mask, &bk0, &bk1);                              \
    entry->meta.cur_hash = h.val32[0];                                        \
    for (unsigned pass = 0u; pass < 2u; pass++) {                             \
        unsigned bki = (pass == 0u) ? bk0 : bk1;                              \
        struct rix_hash_bucket_s *bk = &buckets[bki];                         \
        u32 nilm = RIX_HASH_FIND_U32X16(bk->hash, 0u);                       \
        if (nilm != 0u) {                                                     \
            unsigned s = (unsigned)__builtin_ctz(nilm);                       \
            bk->hash[s] = fp;                                                 \
            bk->idx[s] = FTG_LAYOUT_ENTRY_INDEX(ft, entry);                   \
            if (pass == 1u)                                                   \
                entry->meta.cur_hash = h.val32[1];                            \
            entry->meta.slot = (u16)s;                                   \
            FTG_ON_INSERT_SUCCESS(entry, flag_active);                        \
            head->rhh_nb++;                                                   \
            return 0;                                                         \
        }                                                                     \
    }                                                                         \
    {                                                                         \
        int pos;                                                              \
        unsigned bki;                                                         \
        struct rix_hash_bucket_s *bk;                                         \
        pos = _FTG_HT(p, kickout)(buckets, _FTG_INT(p, hash_base_)(ft),       \
                                  mask, bk0, RIX_HASH_FOLLOW_DEPTH);          \
        if (pos >= 0) {                                                       \
            bki = bk0;                                                        \
        } else {                                                              \
            pos = _FTG_HT(p, kickout)(buckets,                                \
                                      _FTG_INT(p, hash_base_)(ft),            \
                                      mask, bk1, RIX_HASH_FOLLOW_DEPTH);      \
            if (pos < 0)                                                      \
                return -1;                                                    \
            bki = bk1;                                                        \
            entry->meta.cur_hash = h.val32[1];                                \
        }                                                                     \
        bk = &buckets[bki];                                                   \
        bk->hash[pos] = fp;                                                   \
        bk->idx[pos] = FTG_LAYOUT_ENTRY_INDEX(ft, entry);                     \
        entry->meta.slot = (u16)(unsigned)pos;                           \
        FTG_ON_INSERT_SUCCESS(entry, flag_active);                            \
        head->rhh_nb++;                                                       \
        return 0;                                                             \
    }                                                                         \
}                                                                             \
                                                                               \
/* --- init_ex ----------------------------------------------------------- */ \
                                                                               \
static int                                                                           \
_FTG_API(p, init_ex)(_FTG_TABLE_T(p) *ft,                                     \
                     void *array,                                             \
                     unsigned max_entries,                                    \
                     size_t stride,                                           \
                     size_t entry_offset,                                     \
                     const _FTG_CONFIG_T(p) *cfg)                             \
{                                                                             \
    _FTG_CONFIG_T(p) defcfg;                                                  \
    struct rix_hash_bucket_s *buckets;                                        \
    unsigned start_nb_bk, max_nb_bk;                                          \
                                                                               \
    if (ft == NULL || array == NULL || max_entries == 0u)                     \
        return -1;                                                            \
    memset(&defcfg, 0, sizeof(defcfg));                                       \
    if (cfg == NULL)                                                          \
        cfg = &defcfg;                                                        \
    if (cfg->bucket_alloc.alloc == NULL ||                                    \
        cfg->bucket_alloc.free == NULL)                                       \
        return -1;                                                            \
                                                                               \
    RIX_ASSERT(stride >= sizeof(_FTG_ENTRY_T(p)));                            \
    RIX_ASSERT(entry_offset + sizeof(_FTG_ENTRY_T(p)) <= stride);             \
    RIX_ASSERT(FT_PTR_IS_ALIGNED(FT_BYTE_PTR_ADD(array, entry_offset),        \
                                 _Alignof(_FTG_ENTRY_T(p))));                 \
                                                                               \
    start_nb_bk = cfg->start_nb_bk                                            \
        ? ft_roundup_pow2_u32(cfg->start_nb_bk)                               \
        : _FTG_INT(p, default_start_nb_bk_)(max_entries);                     \
    max_nb_bk = cfg->max_nb_bk                                                \
        ? ft_roundup_pow2_u32(cfg->max_nb_bk)                                 \
        : (default_max_nb_bk);                                                \
    if (start_nb_bk < _FTG_INT(p, default_start_nb_bk_)(max_entries))         \
        start_nb_bk = _FTG_INT(p, default_start_nb_bk_)(max_entries);         \
    if (max_nb_bk < start_nb_bk)                                              \
        max_nb_bk = start_nb_bk;                                              \
                                                                               \
    memset(ft, 0, sizeof(*ft));                                               \
    ft->bucket_alloc = cfg->bucket_alloc;                                     \
    ft->grow_fill_pct = cfg->grow_fill_pct                                    \
        ? cfg->grow_fill_pct                                                  \
        : (default_grow_fill_pct);                                            \
    ft->ts_shift = (u8)((cfg->ts_shift != 0u)                            \
        ? flow_timestamp_shift_clamp(cfg->ts_shift)                          \
        : FLOW_TIMESTAMP_DEFAULT_SHIFT);                                      \
    ft->max_entries = max_entries;                                            \
    ft->max_nb_bk = max_nb_bk;                                                \
    ft->start_mask = start_nb_bk - 1u;                                        \
    _FTG_INT(p, init_storage_)(ft, array, stride, entry_offset);              \
                                                                               \
    if (_FTG_INT(p, alloc_buckets_)(ft, start_nb_bk, &buckets) != 0)          \
        return -1;                                                            \
    ft->buckets = buckets;                                                    \
    ft->nb_bk = start_nb_bk;                                                  \
    _FTG_HT(p, init)(&ft->ht_head, start_nb_bk);                              \
    return 0;                                                                 \
}                                                                             \
                                                                               \
/* --- destroy ----------------------------------------------------------- */ \
                                                                               \
static void                                                                          \
_FTG_API(p, destroy)(_FTG_TABLE_T(p) *ft)                                     \
{                                                                             \
    if (ft == NULL)                                                           \
        return;                                                               \
    if (ft->buckets != NULL && ft->bucket_alloc.free != NULL) {               \
        ft->bucket_alloc.free(ft->buckets,                                    \
                              _FTG_INT(p, bucket_bytes_)(ft->nb_bk),          \
                              _Alignof(struct rix_hash_bucket_s),             \
                              ft->bucket_alloc.arg);                          \
    }                                                                         \
    memset(ft, 0, sizeof(*ft));                                               \
}                                                                             \
                                                                               \
/* --- flush ------------------------------------------------------------- */ \
                                                                               \
static void                                                                          \
_FTG_API(p, flush)(_FTG_TABLE_T(p) *ft)                                       \
{                                                                             \
    if (ft == NULL || ft->buckets == NULL)                                    \
        return;                                                               \
    _FTG_FLUSH_BODY(p, ft);                                                   \
    fcore_status_reset(&ft->status, 0u);                                      \
}                                                                             \
                                                                               \
/* --- nb_entries -------------------------------------------------------- */ \
                                                                               \
static unsigned                                                                      \
_FTG_API(p, nb_entries)(const _FTG_TABLE_T(p) *ft)                            \
{                                                                             \
    return ft == NULL ? 0u : ft->ht_head.rhh_nb;                              \
}                                                                             \
                                                                               \
static unsigned                                                                      \
_FTG_API(p, nb_bk)(const _FTG_TABLE_T(p) *ft)                                 \
{                                                                             \
    return ft == NULL ? 0u : ft->nb_bk;                                       \
}                                                                             \
                                                                               \
static void                                                                          \
_FTG_API(p, stats)(const _FTG_TABLE_T(p) *ft,                                 \
                   _FTG_STATS_T(p) *out)                                      \
{                                                                             \
    if (out == NULL)                                                          \
        return;                                                               \
    if (ft == NULL) {                                                         \
        memset(out, 0, sizeof(*out));                                         \
        return;                                                               \
    }                                                                         \
    *out = ft->stats;                                                         \
}                                                                             \
                                                                               \
static void                                                                          \
_FTG_API(p, status)(const _FTG_TABLE_T(p) *ft,                                \
                    struct fcore_status *out)                                 \
{                                                                             \
    if (out == NULL)                                                          \
        return;                                                               \
    if (ft == NULL) {                                                         \
        memset(out, 0, sizeof(*out));                                         \
        return;                                                               \
    }                                                                         \
    *out = ft->status;                                                        \
}                                                                             \
                                                                               \
/* --- find_bulk --------------------------------------------------------- */ \
                                                                               \
static void                                                                          \
_FTG_API(p, find_bulk)(_FTG_TABLE_T(p) *ft,                                   \
                       const _FTG_KEY_T(p) *keys,                             \
                       unsigned nb_keys,                                      \
                       u64 now,                                          \
                       _FTG_RESULT_T(p) *results)                             \
{                                                                             \
    if (results == NULL)                                                      \
        return;                                                               \
    if (ft == NULL || ft->buckets == NULL || keys == NULL) {                  \
        for (unsigned i = 0; i < nb_keys; i++)                                \
            results[i].entry_idx = 0u;                                        \
        return;                                                               \
    }                                                                         \
    _FTG_FIND_BULK_BODY(p, ft, keys, nb_keys, now, results, hash_fn, cmp_fn);\
}                                                                             \
                                                                               \
/* --- add_idx_bulk ------------------------------------------------------ */ \
                                                                               \
static unsigned                                                                      \
_FTG_API(p, add_idx_bulk)(_FTG_TABLE_T(p) *ft,                                \
                           u32 *entry_idxv,                              \
                           unsigned nb_keys,                                  \
                           enum ft_add_policy policy,                         \
                           u64 now,                                      \
                           u32 *unused_idxv)                             \
{                                                                             \
    if (unused_idxv == NULL)                                                  \
        return 0u;                                                            \
    if (ft == NULL || ft->buckets == NULL || entry_idxv == NULL) {            \
        return 0u;                                                            \
    }                                                                         \
    _FTG_ADD_ENTRY_BULK2_BODY(p, ft, entry_idxv, nb_keys, policy, now, unused_idxv,\
                              hash_fn, cmp_fn);                               \
}                                                                             \
                                                                               \
/* --- del_key_bulk ------------------------------------------------------ */ \
                                                                               \
static unsigned                                                               \
_FTG_API(p, del_key_bulk)(_FTG_TABLE_T(p) *ft,                                \
                          const _FTG_KEY_T(p) *keys,                          \
                          unsigned nb_keys,                                   \
                          u32 *unused_idxv)                                   \
{                                                                             \
    if (ft == NULL || keys == NULL || ft->buckets == NULL ||                  \
        unused_idxv == NULL)                                                  \
        return 0u;                                                            \
    _FTG_DEL_KEY_BULK_BODY(p, ft, keys, nb_keys, unused_idxv,                \
                            hash_fn, cmp_fn);                                 \
}                                                                             \
                                                                               \
/* --- del_idx_bulk ------------------------------------------------ */ \
                                                                               \
static void                                                                   \
_FTG_API(p, del_idx_bulk)(_FTG_TABLE_T(p) *ft,                          \
                                const u32 *entry_idxv,                   \
                                unsigned nb_keys)                             \
{                                                                             \
    if (ft == NULL || ft->buckets == NULL || entry_idxv == NULL)              \
        return;                                                               \
    _FTG_DEL_ENTRY_IDX_BULK_BODY(p, ft, entry_idxv, nb_keys);                 \
}                                                                             \
                                                                               \
/* --- walk -------------------------------------------------------------- */ \
                                                                               \
static int                                                                           \
_FTG_API(p, walk)(_FTG_TABLE_T(p) *ft,                                        \
                  int (*cb)(u32 entry_idx, void *arg),                   \
                  void *arg)                                                  \
{                                                                             \
    if (ft == NULL || cb == NULL)                                             \
        return -1;                                                            \
    _FTG_WALK_BODY(p, ft, cb, arg);                                           \
    return 0;                                                                 \
}                                                                             \
                                                                               \
/* --- grow_2x ----------------------------------------------------------- */ \
                                                                               \
static int                                                                           \
_FTG_API(p, grow_2x)(_FTG_TABLE_T(p) *ft)                                     \
{                                                                             \
    struct rix_hash_bucket_s *new_buckets;                                    \
    _FTG_HT_T(p) new_head;                                                    \
    struct { _FTG_ENTRY_T(p) *entry; union rix_hash_hash_u hash; }            \
        ctx[FT_TABLE_GROW_CTX_RING];                                          \
    unsigned new_nb_bk, new_mask, old_mask;                                   \
    unsigned produced = 0u, consumed = 0u;                                    \
                                                                               \
    if (ft == NULL || ft->buckets == NULL)                                    \
        return -1;                                                            \
    if (ft->nb_bk >= ft->max_nb_bk) {                                         \
        ft->stats.grow_failures++;                                            \
        return -1;                                                            \
    }                                                                         \
    new_nb_bk = ft->nb_bk << 1;                                               \
    if (new_nb_bk == 0u || new_nb_bk > ft->max_nb_bk) {                       \
        ft->stats.grow_failures++;                                            \
        return -1;                                                            \
    }                                                                         \
    if (_FTG_INT(p, alloc_buckets_)(ft, new_nb_bk, &new_buckets) != 0) {      \
        ft->stats.grow_failures++;                                            \
        return -1;                                                            \
    }                                                                         \
    _FTG_HT(p, init)(&new_head, new_nb_bk);                                   \
    new_mask = new_head.rhh_mask;                                             \
    old_mask = ft->ht_head.rhh_mask;                                          \
                                                                               \
    for (unsigned bk = 0u;                                                    \
         bk < FT_TABLE_GROW_OLD_BK_AHEAD && bk <= old_mask;                   \
         bk++)                                                                \
        rix_hash_prefetch_bucket_indices_of(&ft->buckets[bk]);                \
                                                                               \
    for (unsigned bk = 0u; bk <= old_mask; bk++) {                            \
        const struct rix_hash_bucket_s *old_bk = &ft->buckets[bk];            \
        unsigned pfbk = bk + FT_TABLE_GROW_OLD_BK_AHEAD;                      \
        if (pfbk <= old_mask)                                                 \
            rix_hash_prefetch_bucket_indices_of(&ft->buckets[pfbk]);          \
                                                                               \
        for (unsigned s = 0u; s < RIX_HASH_BUCKET_ENTRY_SZ; s++) {            \
            unsigned idx = old_bk->idx[s];                                    \
            _FTG_ENTRY_T(p) *entry;                                           \
            if (idx == (unsigned)RIX_NIL)                                     \
                continue;                                                     \
            entry = FTG_LAYOUT_ENTRY_PTR(ft, idx);                            \
            RIX_ASSUME_NONNULL(entry);                                        \
            rix_hash_prefetch_entry_of(entry);                                \
        }                                                                     \
                                                                               \
        for (unsigned s = 0u; s < RIX_HASH_BUCKET_ENTRY_SZ; s++) {            \
            unsigned idx = old_bk->idx[s];                                    \
            _FTG_ENTRY_T(p) *entry;                                           \
            union rix_hash_hash_u h;                                          \
            unsigned bk0;                                                     \
            if (idx == (unsigned)RIX_NIL)                                     \
                continue;                                                     \
            entry = FTG_LAYOUT_ENTRY_PTR(ft, idx);                            \
            RIX_ASSUME_NONNULL(entry);                                        \
            h = hash_fn(&entry->key, ft->start_mask);                          \
            ctx[produced & (FT_TABLE_GROW_CTX_RING - 1u)].entry = entry;      \
            ctx[produced & (FT_TABLE_GROW_CTX_RING - 1u)].hash = h;           \
            {                                                                 \
                unsigned _bk1;                                                \
                (void)rix_hash_fp(h, new_mask, &bk0, &_bk1);                 \
            }                                                                 \
            rix_hash_prefetch_bucket_hashes_of(&new_buckets[bk0]);            \
            produced++;                                                       \
                                                                               \
            if (produced - consumed > FT_TABLE_GROW_REINSERT_AHEAD) {         \
                unsigned ci = consumed & (FT_TABLE_GROW_CTX_RING - 1u);       \
                if (_FTG_INT(p, rehash_insert_hashed_)(                       \
                        &new_head, new_buckets, ft,                           \
                        ctx[ci].entry, ctx[ci].hash) != 0) {                  \
                    ft->bucket_alloc.free(                                    \
                        new_buckets,                                          \
                        _FTG_INT(p, bucket_bytes_)(new_nb_bk),                \
                        _Alignof(struct rix_hash_bucket_s),                   \
                        ft->bucket_alloc.arg);                                \
                    ft->stats.grow_failures++;                                \
                    return -1;                                                \
                }                                                             \
                consumed++;                                                   \
            }                                                                 \
        }                                                                     \
    }                                                                         \
                                                                               \
    while (consumed < produced) {                                             \
        unsigned ci = consumed & (FT_TABLE_GROW_CTX_RING - 1u);               \
        if (_FTG_INT(p, rehash_insert_hashed_)(                               \
                &new_head, new_buckets, ft,                                   \
                ctx[ci].entry, ctx[ci].hash) != 0) {                          \
            ft->bucket_alloc.free(                                            \
                new_buckets,                                                  \
                _FTG_INT(p, bucket_bytes_)(new_nb_bk),                        \
                _Alignof(struct rix_hash_bucket_s),                           \
                ft->bucket_alloc.arg);                                        \
            ft->stats.grow_failures++;                                        \
            return -1;                                                        \
        }                                                                     \
        consumed++;                                                           \
    }                                                                         \
                                                                               \
    ft->bucket_alloc.free(ft->buckets,                                        \
                          _FTG_INT(p, bucket_bytes_)(ft->nb_bk),              \
                          _Alignof(struct rix_hash_bucket_s),                 \
                          ft->bucket_alloc.arg);                              \
    ft->buckets = new_buckets;                                                \
    ft->ht_head = new_head;                                                   \
    ft->nb_bk = new_nb_bk;                                                    \
    fcore_status_reset(&ft->status, (u32)new_head.rhh_nb);               \
    ft->stats.grow_execs++;                                                   \
    return 0;                                                                 \
}                                                                             \
                                                                               \
/* --- reserve ----------------------------------------------------------- */ \
                                                                               \
static int                                                                           \
_FTG_API(p, reserve)(_FTG_TABLE_T(p) *ft,                                     \
                     unsigned min_entries)                                    \
{                                                                             \
    unsigned required_nb_bk;                                                  \
    if (ft == NULL)                                                           \
        return -1;                                                            \
    ft->stats.reserve_calls++;                                                \
    required_nb_bk = _FTG_INT(p, required_nb_bk_)(                            \
        min_entries, ft->grow_fill_pct);                                      \
    if (required_nb_bk > ft->max_nb_bk)                                       \
        return -1;                                                            \
    while (ft->nb_bk < required_nb_bk) {                                      \
        if (_FTG_API(p, grow_2x)(ft) != 0)                                    \
            return -1;                                                        \
    }                                                                         \
    return 0;                                                                 \
}                                                                             \
/* end FT_TABLE_GENERATE */

/*===========================================================================
 * OPS table macro (used in each arch .c after FT_TABLE_GENERATE)
 *===========================================================================*/
#define _FT_OPS_FNAME(prefix, name)                                           \
    _FTG_CAT(_FTG_CAT(ft_, _FTG_CAT(prefix, _table_##name)), FT_ARCH_SUFFIX)

#define _FT_OPS_TNAME(prefix, suffix)                                         \
    _FTG_CAT(_FTG_CAT(ft_, _FTG_CAT(prefix, _ops)), suffix)

#define FT_OPS_TABLE(prefix, suffix)                                          \
const struct ft_##prefix##_ops _FT_OPS_TNAME(prefix, suffix) = {              \
    /* cold-path */                                                            \
    .init_ex         = _FT_OPS_FNAME(prefix, init_ex),                        \
    .destroy         = _FT_OPS_FNAME(prefix, destroy),                        \
    .flush           = _FT_OPS_FNAME(prefix, flush),                          \
    .nb_entries      = _FT_OPS_FNAME(prefix, nb_entries),                     \
    .nb_bk           = _FT_OPS_FNAME(prefix, nb_bk),                         \
    .stats           = _FT_OPS_FNAME(prefix, stats),                          \
    .status          = _FT_OPS_FNAME(prefix, status),                         \
    .walk            = _FT_OPS_FNAME(prefix, walk),                           \
    .grow_2x         = _FT_OPS_FNAME(prefix, grow_2x),                       \
    .reserve         = _FT_OPS_FNAME(prefix, reserve),                        \
    /* hot-path */                                                             \
    .find_bulk       = _FT_OPS_FNAME(prefix, find_bulk),                      \
    .add_idx_bulk    = _FT_OPS_FNAME(prefix, add_idx_bulk),                   \
    .del_key_bulk    = _FT_OPS_FNAME(prefix, del_key_bulk),                    \
    .del_idx_bulk    = _FT_OPS_FNAME(prefix, del_idx_bulk),             \
}

#endif /* _FT_TABLE_GENERATE_H_ */
